# Generated by Django 5.0.7 on 2025-10-04 15:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_core', '0002_savedquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='savedquestion',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question')},
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='is_answered',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='topic',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='savedquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='interview_core.interviewquestion'),
        ),
        migrations.AlterField(
            model_name='savedquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='audio_file',
            field=models.FileField(upload_to='answers/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='interview_core.interviewquestion'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['user', 'topic'], name='interview_c_user_id_a26f65_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['user', 'is_answered'], name='interview_c_user_id_ec18f1_idx'),
        ),
        migrations.AddIndex(
            model_name='savedquestion',
            index=models.Index(fields=['user', 'saved_at'], name='interview_c_user_id_ed3e03_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'created_at'], name='interview_c_user_id_2583cf_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question', 'created_at'], name='interview_c_questio_2f7af1_idx'),
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='timestamp',
        ),
    ]
