# Generated by Django 5.0.7 on 2025-10-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_core', '0003_alter_interviewquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='audio_file',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_text',
            field=models.TextField(default='No transcription available'),
            preserve_default=False,
        ),
    ]
