# Generated by Django 5.0.7 on 2025-10-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_core', '0004_remove_useranswer_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='clarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='completeness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='improvements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='missing_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='technical_accuracy_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
