# Generated by Django 5.0.7 on 2025-11-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_core', '0006_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
    ]
